global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Reactive Gateway
  - job_name: 'reactive-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_timeout: 5s
    honor_labels: true

  # Additional monitoring targets can be added here
  - job_name: 'grpc-services'
    static_configs:
      - targets: ['host.docker.internal:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s